var items_unfamiliar = [
  {
    category: "gems",
    condition: "unfamiliar",
    exemplar: "zircons",
    sentence: "all zircons are gems",
  },
  {
    category: "gems",
    condition: "unfamiliar",
    exemplar: "topazes",
    sentence: "all topazes are gems",
  },
  {
    category: "gems",
    condition: "unfamiliar",
    exemplar: "garnets",
    sentence: "all garnets are gems",
  },
  {
    category: "gems",
    condition: "unfamiliar",
    exemplar: "amethysts",
    sentence: "all amethysts are gems",
  },
  {
    category: "gems",
    condition: "unfamiliar",
    exemplar: "citrines",
    sentence: "all citrines are gems",
  },
  {
    category: "gems",
    condition: "unfamiliar",
    exemplar: "quartzes",
    sentence: "all quartzes are gems",
  },
  {
    category: "pants",
    condition: "unfamiliar",
    exemplar: "jodhpurs",
    sentence: "all jodhpurs are pants",
  },
  {
    category: "pants",
    condition: "unfamiliar",
    exemplar: "khakis",
    sentence: "all khakis are pants",
  },
  {
    category: "pants",
    condition: "unfamiliar",
    exemplar: "dungarees",
    sentence: "all dungarees are pants",
  },
  {
    category: "pants",
    condition: "unfamiliar",
    exemplar: "knickers",
    sentence: "all knickers are pants",
  },
  {
    category: "pants",
    condition: "unfamiliar",
    exemplar: "breeches",
    sentence: "all breeches are pants",
  },
  {
    category: "pants",
    condition: "unfamiliar",
    exemplar: "pantaloons",
    sentence: "all pantaloons are pants",
  },
  {
    category: "instruments",
    condition: "unfamiliar",
    exemplar: "mandolins",
    sentence: "all mandolins are instruments",
  },
  {
    category: "instruments",
    condition: "unfamiliar",
    exemplar: "lutes",
    sentence: "all lutes are instruments",
  },
  {
    category: "instruments",
    condition: "unfamiliar",
    exemplar: "timpanis",
    sentence: "all timpanis are instruments",
  },
  {
    category: "instruments",
    condition: "unfamiliar",
    exemplar: "cymbals",
    sentence: "all cymbals are instruments",
  },
  {
    category: "instruments",
    condition: "unfamiliar",
    exemplar: "sitars",
    sentence: "all sitars are instruments",
  },
  {
    category: "instruments",
    condition: "unfamiliar",
    exemplar: "bugles",
    sentence: "all bugles are instruments",
  },
  {
    category: "fruit",
    condition: "unfamiliar",
    exemplar: "durians",
    sentence: "all durians are fruit",
  },
  {
    category: "fruit",
    condition: "unfamiliar",
    exemplar: "rambutans",
    sentence: "all rambutans are fruit",
  },
  {
    category: "fruit",
    condition: "unfamiliar",
    exemplar: "pomelos",
    sentence: "all pomelos are fruit",
  },
  {
    category: "fruit",
    condition: "unfamiliar",
    exemplar: "tangerines",
    sentence: "all tangerines are fruit",
  },
  {
    category: "fruit",
    condition: "unfamiliar",
    exemplar: "guavas",
    sentence: "all guavas are fruit",
  },
  {
    category: "fruit",
    condition: "unfamiliar",
    exemplar: "quinces",
    sentence: "all quinces are fruit",
  },
  {
    category: "shoes",
    condition: "unfamiliar",
    exemplar: "loafers",
    sentence: "all loafers are shoes",
  },
  {
    category: "shoes",
    condition: "unfamiliar",
    exemplar: "plimsoles",
    sentence: "all plimsoles are shoes",
  },
  {
    category: "shoes",
    condition: "unfamiliar",
    exemplar: "galoshes",
    sentence: "all galoshes are shoes",
  },
  {
    category: "shoes",
    condition: "unfamiliar",
    exemplar: "moccasins",
    sentence: "all moccasins are shoes",
  },
  {
    category: "shoes",
    condition: "unfamiliar",
    exemplar: "espadrilles",
    sentence: "all espadrilles are shoes",
  },
  {
    category: "shoes",
    condition: "unfamiliar",
    exemplar: "stilettos",
    sentence: "all stilettos are shoes",
  },
  {
    category: "mammals",
    condition: "unfamiliar",
    exemplar: "dugongs",
    sentence: "all dugongs are mammals",
  },
  {
    category: "mammals",
    condition: "unfamiliar",
    exemplar: "lemmings",
    sentence: "all lemmings are mammals",
  },
  {
    category: "mammals",
    condition: "unfamiliar",
    exemplar: "bilbies",
    sentence: "all bilbies are mammals",
  },
  {
    category: "mammals",
    condition: "unfamiliar",
    exemplar: "coyotes",
    sentence: "all coyotes are mammals",
  },
  {
    category: "mammals",
    condition: "unfamiliar",
    exemplar: "tapirs",
    sentence: "all tapirs are mammals",
  },
  {
    category: "mammals",
    condition: "unfamiliar",
    exemplar: "raccoons",
    sentence: "all raccoons are mammals",
  },
  {
    category: "weapons",
    condition: "unfamiliar",
    exemplar: "nunchucks",
    sentence: "all nunchucks are weapons",
  },
  {
    category: "weapons",
    condition: "unfamiliar",
    exemplar: "bazookas",
    sentence: "all bazookas are weapons",
  },
  {
    category: "weapons",
    condition: "unfamiliar",
    exemplar: "cutlasses",
    sentence: "all cutlasses are weapons",
  },
  {
    category: "weapons",
    condition: "unfamiliar",
    exemplar: "katanas",
    sentence: "all katanas are weapons",
  },
  {
    category: "weapons",
    condition: "unfamiliar",
    exemplar: "scimitars",
    sentence: "all scimitars are weapons",
  },
  {
    category: "weapons",
    condition: "unfamiliar",
    exemplar: "molotovs",
    sentence: "all molotovs are weapons",
  },
  {
    category: "birds",
    condition: "unfamiliar",
    exemplar: "starlings",
    sentence: "all starlings are birds",
  },
  {
    category: "birds",
    condition: "unfamiliar",
    exemplar: "plovers",
    sentence: "all plovers are birds",
  },
  {
    category: "birds",
    condition: "unfamiliar",
    exemplar: "wrens",
    sentence: "all wrens are birds",
  },
  {
    category: "birds",
    condition: "unfamiliar",
    exemplar: "kestrels",
    sentence: "all kestrels are birds",
  },
  {
    category: "birds",
    condition: "unfamiliar",
    exemplar: "ospreys",
    sentence: "all ospreys are birds",
  },
  {
    category: "birds",
    condition: "unfamiliar",
    exemplar: "galahs",
    sentence: "all galahs are birds",
  },
  {
    category: "insects",
    condition: "unfamiliar",
    exemplar: "cicadas",
    sentence: "all cicadas are insects",
  },
  {
    category: "insects",
    condition: "unfamiliar",
    exemplar: "aphids",
    sentence: "all aphids are insects",
  },
  {
    category: "insects",
    condition: "unfamiliar",
    exemplar: "locusts",
    sentence: "all locusts are insects",
  },
  {
    category: "insects",
    condition: "unfamiliar",
    exemplar: "weevils",
    sentence: "all weevils are insects",
  },
  {
    category: "insects",
    condition: "unfamiliar",
    exemplar: "earwigs",
    sentence: "all earwigs are insects",
  },
  {
    category: "insects",
    condition: "unfamiliar",
    exemplar: "slaters",
    sentence: "all slaters are insects",
  },
  {
    category: "trees",
    condition: "unfamiliar",
    exemplar: "hickories",
    sentence: "all hickories are trees",
  },
  {
    category: "trees",
    condition: "unfamiliar",
    exemplar: "larches",
    sentence: "all larches are trees",
  },
  {
    category: "trees",
    condition: "unfamiliar",
    exemplar: "sycamores",
    sentence: "all sycamores are trees",
  },
  {
    category: "trees",
    condition: "unfamiliar",
    exemplar: "junipers",
    sentence: "all junipers are trees",
  },
  {
    category: "trees",
    condition: "unfamiliar",
    exemplar: "poplars",
    sentence: "all poplars are trees",
  },
  {
    category: "trees",
    condition: "unfamiliar",
    exemplar: "cedars",
    sentence: "all cedars are trees",
  },
];